name: Scrape ChatGPT with Selenium

on:
  schedule:
    - cron: "0 2 * * *"  # Run daily at 2 AM UTC
  workflow_dispatch:      # Manual trigger available

permissions:
  contents: write
  issues: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    env:
      PYTHON_VERSION: "3.10"
      
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Set up Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable chromium-chromedriver
          sudo ln -s /usr/bin/google-chrome /usr/local/bin/google-chrome
          sudo ln -s /usr/bin/chromedriver /usr/local/bin/chromedriver
          
      - name: Create .env file
        run: |
          cat > .env << EOL
          CHROME_DRIVER_PATH=/usr/local/bin/chromedriver
          WEBSITE_URL=https://chat.openai.com
          WAIT_TIMEOUT=60
          REPO_PATH=.
          COMPARISON_OUTPUT=changes.json
          EOL

      - name: Run Selenium Scraper
        run: python scrape_chatgpt.py
        continue-on-error: true

      - name: Check for changes
        id: check-changes
        run: |
          if [ -f changes.json ]; then
            echo "CHANGES_FOUND=$(cat changes.json | jq 'any_values')" >> $GITHUB_ENV
          else
            echo "CHANGES_FOUND=false" >> $GITHUB_ENV
            touch changes.json
          fi

      - name: Create scraped_pages directory
        run: mkdir -p scraped_pages

      - name: Commit and Push Changes
        run: |
          git config --global user.email "feeltheagi@proton.me"
          git config --global user.name "Adam"
          
          # Stage any existing files
          git add -A
          
          # Create commit even if no changes
          git commit -m "Automated Selenium scrape - $(date +%Y%m%d)" || echo "No changes to commit"
          
          # Push if there are changes
          git push || echo "No changes to push"

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Scraper workflow failed',
                body: `Workflow run failed: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
              });
            } catch (error) {
              console.log('Failed to create issue:', error);
            }