name: Scrape ChatGPT with Selenium

on:
  schedule:
    - cron: "0 2 * * *"  # Run daily at 2 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chrome-channel: [ stable, beta, dev ]
    env:
      OPENAI_USERNAME: ${{ secrets.OPENAI_USERNAME }}
      OPENAI_PASSWORD: ${{ secrets.OPENAI_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Build & scrape (${{ matrix.chrome-channel }})
        run: |
          docker build --build-arg CHROME_CHANNEL=${{ matrix.chrome-channel }} -t scraper .
          docker run --rm \
            -e OPENAI_USERNAME \
            -e OPENAI_PASSWORD \
            scraper
